### PR TITLE
PROPOSAL: add license information

### PR DESCRIPTION
**Pull request by jorisvddonk**
This proposal adds license information to the project.
**The contents of this proposal and pull request shall not be considered active licensing information for this project until approved by all contributors explicitly**

I propose that all code/assets are licensed under MIT , unless:
1. explicit other licensing information is available (e.g. because of third party assets from Godot's Asset Library).
2. the content was derived from Noctis IV's assets or source code.

For content derived from Noctis IV, Noctis IV's licensing terms (the WTOF Public License) will be used.

For two assets of my own work, I propose dual-licensing under CC0 and MIT.

### CODE REVIEW

**Comment by jorisvddonk** [comment]
As contributor, I hereby approve the license proposal.

**Comment by jorisvddonk** [comment]
@dgcole as you have made a contribution to this project (https://github.com/jorisvddonk/system-reset/pull/1) I'd like to request your input on this proposal, and should you agree with it, your explicit approval in the form of a comment in this PR.

**Comment by dgcole** [comment]
I approve of the license changes.

**Comment by jorisvddonk** [comment]
Thanks for the quick response! Merging.

**Pull request merged**
